BRUTE-FORCE

# /ip firewall filter
# /ip firewall filter add chain=output protocol=tcp src-port=8291 content="ERROR: wrong username or password" dst-limit=1/1m,2,src-and-dst-addresses/100s action=accept comment="Deteksi Brute-Force"
# /ip firewall filter add chain=output protocol=tcp src-port=8291 content="ERROR: wrong username or password" dst-limit=1/1m,2,src-and-dst-addresses/100s action=add-dst-to-address-list address-list=BlackList address-list-timeout=1d comment="Deteksi Brute-Force"
# /ip firewall filter chain-input protocol=tcp dst-port=8291,22 src-address-list=BlackList address-list-timeout=1d action=drop

# /ip firewall filter add chain=input protocol=tcp dst-port=22 connection-state=new action=add-src-to-address-list address-list=BlackList address-list-timeout=1d comment="Deteksi Brute-Force"

# Urutan
  drop
  acc
  add





# CA
# apt install openssl easy-rsa ssl-cert
# cd /home
# mkdir Cert
# cd Cert
# openssl req -x509 -new -nodes -out rootUKK-D4vi1d.crt -keyout rootUKK-D4vi1d.key
# openssl req -new -nodes -days 365 -out UKK.Web.csr -keyout UKK.Web.key
# openssl x509 -req -CA rootUKK-D4vi1d.crt -CAkey rootUKK-D4vi1d.key -set_serial 01 -in UKK.Web.csr -out UKK.Web.crt
# cp -r /home/Cert/* /etc/ssl/
# cp rootUKK-D4vi1d /home/Share
# /usr/sbin/a2enmod sll